// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.7.0.0
//      SpecFlow Generator Version:3.7.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BDDElectricityBillKata.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.7.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("FCA Charges Calculation", Description="\tAs a user I should be be able to calculate the FCA charges which means the Fuel " +
        "Cost Adjustment.\r\n\tE = A (units) * 0.13 i.e. 13 paise per unit", SourceFile="Features\\FCACharges.feature", SourceLine=0)]
    public partial class FCAChargesCalculationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "FCACharges.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "FCA Charges Calculation", "\tAs a user I should be be able to calculate the FCA charges which means the Fuel " +
                    "Cost Adjustment.\r\n\tE = A (units) * 0.13 i.e. 13 paise per unit", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void CalculateTheFCAChargesForTheDomesticElectricityConsumerOnTheUnitsBilled(string units, string fcatotal, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("units", units);
            argumentsOfScenario.Add("fcatotal", fcatotal);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate the FCA Charges for the Domestic Electricity Consumer on the units bill" +
                    "ed", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 testRunner.Given(string.Format("I consumed {0} units in a month", units), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 7
 testRunner.When("the state ABC electricity bill gets generated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 8
 testRunner.Then(string.Format("the total energy charges as amounted to Rs {0}", fcatotal), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Calculate the FCA Charges for the Domestic Electricity Consumer on the units bill" +
            "ed, 40", SourceLine=12)]
        public virtual void CalculateTheFCAChargesForTheDomesticElectricityConsumerOnTheUnitsBilled_40()
        {
#line 5
this.CalculateTheFCAChargesForTheDomesticElectricityConsumerOnTheUnitsBilled("40", "5.2", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Calculate the FCA Charges for the Domestic Electricity Consumer on the units bill" +
            "ed, 100", SourceLine=12)]
        public virtual void CalculateTheFCAChargesForTheDomesticElectricityConsumerOnTheUnitsBilled_100()
        {
#line 5
this.CalculateTheFCAChargesForTheDomesticElectricityConsumerOnTheUnitsBilled("100", "13", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Calculate the FCA Charges for the Domestic Electricity Consumer on the units bill" +
            "ed, 350", SourceLine=12)]
        public virtual void CalculateTheFCAChargesForTheDomesticElectricityConsumerOnTheUnitsBilled_350()
        {
#line 5
this.CalculateTheFCAChargesForTheDomesticElectricityConsumerOnTheUnitsBilled("350", "45.5", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
